# Generated by Django 5.0.7 on 2024-07-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
